// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiL35RGG4u-kFPz_3RQT2vFVganHQDpWU',
    appId: '1:37480233620:web:260bccf6673fa3faae5281',
    messagingSenderId: '37480233620',
    projectId: 'websocket-chat-app-46bfe',
    authDomain: 'websocket-chat-app-46bfe.firebaseapp.com',
    storageBucket: 'websocket-chat-app-46bfe.appspot.com',
    measurementId: 'G-Y2L729CZCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFSDWPCTWVYW4eNqbvS3j3nKJXHvglWI',
    appId: '1:37480233620:android:11257101f8a1659fae5281',
    messagingSenderId: '37480233620',
    projectId: 'websocket-chat-app-46bfe',
    storageBucket: 'websocket-chat-app-46bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNAJ3BfMG8Hq7qKpRXEJWROlGWsHlQ_bs',
    appId: '1:37480233620:ios:ed17c865fa6a623fae5281',
    messagingSenderId: '37480233620',
    projectId: 'websocket-chat-app-46bfe',
    storageBucket: 'websocket-chat-app-46bfe.appspot.com',
    iosBundleId: 'com.example.chatAppUsingSocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNAJ3BfMG8Hq7qKpRXEJWROlGWsHlQ_bs',
    appId: '1:37480233620:ios:ed17c865fa6a623fae5281',
    messagingSenderId: '37480233620',
    projectId: 'websocket-chat-app-46bfe',
    storageBucket: 'websocket-chat-app-46bfe.appspot.com',
    iosBundleId: 'com.example.chatAppUsingSocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiL35RGG4u-kFPz_3RQT2vFVganHQDpWU',
    appId: '1:37480233620:web:4f00ba7c3874c594ae5281',
    messagingSenderId: '37480233620',
    projectId: 'websocket-chat-app-46bfe',
    authDomain: 'websocket-chat-app-46bfe.firebaseapp.com',
    storageBucket: 'websocket-chat-app-46bfe.appspot.com',
    measurementId: 'G-K5QKQL1M2C',
  );
}
