// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSsl7a9ZilE0Uka7iCC6UF8Wme3Mmuk30',
    appId: '1:212406031535:web:8776c880537d5765b1f05a',
    messagingSenderId: '212406031535',
    projectId: 'chat-app-df249',
    authDomain: 'chat-app-df249.firebaseapp.com',
    storageBucket: 'chat-app-df249.appspot.com',
    measurementId: 'G-TPLXK01278',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5dic42B1qDLBokZhn6HmLimmLCEg5LlA',
    appId: '1:212406031535:android:0b9337b1dc84198bb1f05a',
    messagingSenderId: '212406031535',
    projectId: 'chat-app-df249',
    storageBucket: 'chat-app-df249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjAoGMXrrEXVW1rT_EdCL14vlzSISAoM',
    appId: '1:212406031535:ios:4382783b5c7ee544b1f05a',
    messagingSenderId: '212406031535',
    projectId: 'chat-app-df249',
    storageBucket: 'chat-app-df249.appspot.com',
    iosBundleId: 'com.example.chatAppUsingSocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIjAoGMXrrEXVW1rT_EdCL14vlzSISAoM',
    appId: '1:212406031535:ios:4382783b5c7ee544b1f05a',
    messagingSenderId: '212406031535',
    projectId: 'chat-app-df249',
    storageBucket: 'chat-app-df249.appspot.com',
    iosBundleId: 'com.example.chatAppUsingSocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSsl7a9ZilE0Uka7iCC6UF8Wme3Mmuk30',
    appId: '1:212406031535:web:3b5bfe3e0d2f89abb1f05a',
    messagingSenderId: '212406031535',
    projectId: 'chat-app-df249',
    authDomain: 'chat-app-df249.firebaseapp.com',
    storageBucket: 'chat-app-df249.appspot.com',
    measurementId: 'G-F3811ZPZ1M',
  );
}
